Skateshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("paginas.urls")),
    path("", include("cadastros.urls")),
    path("", include("usuarios.urls")),

    path("__debug__/", include("debug_toolbar.urls")),
]

cadastros/urls.py
from django.urls import path
from .views import CarrinhoCreate, CarrinhoDelete, CarrinhoList, CarrinhoUpdate, ClienteAutocomplete, ClienteCreate, ClienteDelete, ClienteList, ClienteUpdate, ProdutoPedidoList
from .views import ProdutoList, MarcaList, MarcaCreate, MarcaUpdate
from .views import ProdutoCreate, ProdutoUpdate
from .views import MarcaDelete, ProdutoDelete
from .views import FuncionarioCreate, FuncionarioUpdate, FuncionárioDelete, FuncionarioList
from .views import PedidoCreate, PedidoList, PedidoDelete


urlpatterns = [

    # URLS MARCA

    path("cadastrar/marca", MarcaCreate.as_view(), name="cadastrar-marca"),
    path("atualizar/marca/<int:pk>/",
         MarcaUpdate.as_view(), name="atualizar-marca"),
    path("listar/marca", MarcaList.as_view(), name="listar-marca"),
    path("excluir/marca/<int:pk>/", MarcaDelete.as_view(), name="excluir-marca"),

    # URLS PRODUTO

    path("cadastrar/produto", ProdutoCreate.as_view(), name="cadastrar-produto"),
    path("atualizar/produto/<int:pk>/",
         ProdutoUpdate.as_view(), name="atualizar-produto"),
    path("listar/produto", ProdutoList.as_view(), name="listar-produto"),
    path("excluir/produto/<int:pk>/",
         ProdutoDelete.as_view(), name="excluir-produto"),

    # URLS CLIENTE

    path("cadastrar/cliente", ClienteCreate.as_view(), name="cadastrar-cliente"),
    path("atualizar/cliente/<int:pk>/",
         ClienteUpdate.as_view(), name="atualizar-cliente"),
    path("listar/cliente", ClienteList.as_view(), name="listar-cliente"),
    path("excluir/cliente/<int:pk>/",
         ClienteDelete.as_view(), name="excluir-cliente"),

    # URLS FUNCIONARIO

    path("cadastrar/funcionario", FuncionarioCreate.as_view(),
         name="cadastrar-funcionario"),
    path("atualizar/funcionario/<int:pk>/",
         FuncionarioUpdate.as_view(), name="atualizar-funcionario"),
    path("listar/cliente", FuncionarioList.as_view(), name="listar-funcionario"),
    path("excluir/cliente/<int:pk>/",
         FuncionárioDelete.as_view(), name="excluir-funcionario"),







    path("cadastrar/pedido", PedidoCreate.as_view(), name="cadastrar-pedido"),
    path("listar/pedido", PedidoList.as_view(), name="listar-pedido"),
    path("excluir/pedido/<int:pk>/", PedidoDelete.as_view(), name="excluir-pedido"),
    path("listar/produtos/pedido/<int:pk_pedido>/", ProdutoPedidoList.as_view(),
         name="listar-produtos-pedido"),

    path("cadastrar/carrinho", CarrinhoCreate.as_view(), name="cadastrar-carrinho"),
    path("atualizar/carrinho/<int:pk>/",
         CarrinhoUpdate.as_view(), name="atualizar-carrinho"),
    path("listar/carrinho", CarrinhoList.as_view(), name="listar-carrinho"),
    path("excluir/carrinho/<int:pk>/",
         CarrinhoDelete.as_view(), name="excluir-carrinho"),
    path("buscar/cliente", ClienteAutocomplete.as_view(), name="buscar-cliente")

]

paginas/urls.py
from django.urls import path, include
from .views import IndexView, SobreView

urlpatterns = [
    path("", IndexView.as_view(), name='index'),
    path("sobre", SobreView.as_view(), name='pagina-sobre'),
    
]

cadastros/models.py
from django.db import models

# Create your models here.


class Marca(models.Model):
    nome = models.CharField(max_length=55)

    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nome


class Produto(models.Model):
    nome = models.CharField(max_length=55)
    preco = models.DecimalField(
        decimal_places=2, max_digits=9, verbose_name="Preço")
    codigo = models.IntegerField(verbose_name="Código")
    marca = models.ForeignKey(
        Marca, on_delete=models.PROTECT, help_text="Selecione a Marca")

    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Nome: {self.nome} | R${self.preco} | Código: {self.codigo} | Marca: {self.marca.nome}"


class Cliente(models.Model):
    nome = models.CharField(max_length=55)
    cpf = models.CharField(max_length=14, verbose_name="CPF", unique=True)
    telefone = models.CharField(max_length=15)
    cep = models.CharField(max_length=10, verbose_name="CEP")
    logradouro = models.CharField(max_length=100)
    numero = models.CharField(max_length=20, verbose_name="Número", null=True, blank=True)
    bairro = models.CharField(max_length=50, null=True, blank=True)
    cidade = models.CharField(max_length=50)

    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Nome: {self.nome} | CPF: {self.cpf} | Telefone: {self.telefone}"


class Pagamento(models.Model):
    valor_recebido = models.DecimalField(
        decimal_places=2, max_digits=9, verbose_name="Valor Recebido")
    valor_parcela = models.DecimalField(
        decimal_places=2, max_digits=9, verbose_name="Valor da Parcela")
    data_vencimento = models.DateField()
    data_pagamento = models.DateField()
    parcelas = models.IntegerField(verbose_name="Parcelas")
    forma_pagamento = models.CharField(
        max_length=55, verbose_name="Forma pagamento")

    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)


class Funcionario(models.Model):
    nome = models.CharField(max_length=55)
    cpf = models.CharField(max_length=14, verbose_name="CPF", unique=True)
    telefone = models.CharField(max_length=15)
    cargo = models.CharField(max_length=55)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Nome: {self.nome} | CPF: {self.cpf} | Telefone: {self.telefone} | Cargo: {self.cargo}"
    

class Pedido(models.Model):
    cliente = models.ForeignKey(
        Cliente, on_delete=models.PROTECT, help_text="Selecione um Cliente")
    valor_total = models.DecimalField(
        decimal_places=2, max_digits=9, verbose_name="Preço")

    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

class ProdutoPedido(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    preco = models.DecimalField(
        decimal_places=2, max_digits=9, verbose_name="Preço")
    quantidade = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.produto.nome} ({self.quantidade})'
    

class Carrinho(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'Produto: {self.produto} | Qtd. {self.quantidade}'

cadastros/forms.py
from dal import autocomplete
from django import forms
from .models import Pedido


class PedidoForms(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ["cliente", "valor_total"]
        widgets = {
            'cliente': autocomplete.ModelSelect2(
                url='buscar-cliente'
            )
        }

cadastros/views.py
from cadastros.forms import PedidoForms
from .models import Carrinho, Cliente, Marca, Pedido, Produto, Funcionario, ProdutoPedido
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from dal import autocomplete

# from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView

from django.contrib.messages.views import SuccessMessageMixin



# CREATE


class MarcaCreate(SuccessMessageMixin, CreateView, LoginRequiredMixin):
    model = Marca
    fields = ["nome"]
    template_name = "cadastros/form.html"
    success_url = reverse_lazy("listar-marca")
    extra_context = {"titulo": "Cadastro de Marca"}
    success_message = "A Marca %(nome)s foi criada com sucesso!"


class ProdutoCreate(SuccessMessageMixin, CreateView, LoginRequiredMixin):
    model = Produto
    fields = ["nome", "preco", "codigo", "marca"]
    template_name = "cadastros/form.html"
    success_url = reverse_lazy("listar-produto")
    extra_context = {"titulo": "Cadastro de Produto"}
    success_message = "O Produto %(nome)s foi criado com sucesso!"



class ClienteCreate(SuccessMessageMixin, CreateView, LoginRequiredMixin):
    model = Cliente
    fields = ["nome", "cpf", "telefone","cep", "logradouro", "numero","bairro","cidade"]
    template_name = "cadastros/form.html"
    success_url = reverse_lazy("listar-cliente")
    extra_context = {"titulo": "Cadastro de Cliente"}
    success_message = "O Cliente %(nome)s foi cadastrado com sucesso!"



class FuncionarioCreate(SuccessMessageMixin, CreateView, LoginRequiredMixin):
    model = Funcionario
    fields = ["nome", "cpf", "telefone", "cargo"]
    template_name = "cadastros/form.html"
    success_url = reverse_lazy("listar-funcionario")
    extra_context = {"titulo": "Cadastro de Funcionário"}
    success_message = "O Funcionário %(nome)s foi cadastrado com sucesso!"



# UPDATE

class MarcaUpdate(SuccessMessageMixin, UpdateView, LoginRequiredMixin):
    model = Marca
    fields = ["nome"]
    template_name = "cadastros/form.html"
    success_url = reverse_lazy("listar-marca")
    extra_context = {"titulo": "Atualizar Marca"}
    success_message = "A Marca %(nome)s foi alterada com sucesso!"



class ProdutoUpdate(SuccessMessageMixin, UpdateView, LoginRequiredMixin):
    model = Produto
    fields = ["nome", "preco", "codigo", "marca"]
    template_name = "cadastros/form.html"
    success_url = reverse_lazy("listar-produto")
    extra_context = {"titulo": "Atualizar Produto"}
    success_message = "O Produto %(nome)s foi alterado com sucesso!"



class ClienteUpdate(SuccessMessageMixin, UpdateView, LoginRequiredMixin):
    model = Cliente
    fields = ["nome", "cpf", "telefone","cep", "logradouro", "numero","bairro","cidade"]
    template_name = "cadastros/form.html"
    success_url = reverse_lazy("listar-cliente")
    extra_context = {"titulo": "Atualizar Cliente"}
    success_message = "O Cliente %(nome)s foi alterado com sucesso!"



class FuncionarioUpdate(SuccessMessageMixin, UpdateView, LoginRequiredMixin):
    model = Funcionario
    fields = ["nome", "cpf", "telefone", "cargo"]
    template_name = "cadastros/form.html"
    success_url = reverse_lazy("listar-funcionario")
    extra_context = {"titulo": "Atualizar Funcionário"}
    success_message = "O Funcionário %(nome)s foi alterado com sucesso!"



# LIST

class MarcaList(ListView, LoginRequiredMixin):
    model = Marca
    template_name = "cadastros/list/marca.html"
    paginate_by = 100


class ProdutoList(ListView, LoginRequiredMixin):
    model = Produto
    template_name = "cadastros/list/produto.html"
    paginate_by = 100


class ClienteList(ListView, LoginRequiredMixin):
    model = Cliente
    template_name = "cadastros/list/cliente.html"
    paginate_by = 100


class FuncionarioList(ListView, LoginRequiredMixin):
    model = Funcionario
    template_name = "cadastros/list/funcionario.html"
    paginate_by = 100


# DELETE

class MarcaDelete(DeleteView, LoginRequiredMixin):
    model = Marca
    template_name = "cadastros/delete.html"
    success_url = reverse_lazy("listar-marca")


class ProdutoDelete(DeleteView, LoginRequiredMixin):
    model = Produto
    template_name = "cadastros/delete.html"
    success_url = reverse_lazy("listar-produto")


class ClienteDelete(DeleteView, LoginRequiredMixin):
    model = Cliente
    template_name = "cadastros/delete.html"
    success_url = reverse_lazy("listar-cliente")


class FuncionárioDelete(DeleteView, LoginRequiredMixin):
    model = Funcionario
    template_name = "cadastros/delete.html"
    success_url = reverse_lazy("listar-funcionario")


class PedidoCreate(LoginRequiredMixin, CreateView):
    form_class = PedidoForms
    template_name = "cadastros/form_pedido.html"
    success_url = reverse_lazy("listar-pedido")
    extra_context = {"titulo": "Cadastro de Pedido"}

    def form_valid(self, form):
        form.instance.valor_total = 0.0

        # cria a venda no banco e o object
        url = super().form_valid(form)

        # faz um select em todos os produtos do carirnho
        produtos_pedido = Carrinho.objects.all()
        valor_total = 0.0

        if (produtos_pedido.count() == 0):
            form.add_error("", "Seu carrinho de compras está vazio!")
            return super().form_invalid(form)

        for i in produtos_pedido:
            valor_total += (float(i.produto.preco) * i.quantidade)

            ProdutoPedido.objects.create(
                produto=i.produto,
                pedido=self.object,
                preco=i.produto.preco * i.quantidade,
                quantidade=i.quantidade
            )

            i.delete()

        self.object.valor_total = valor_total
        self.object.save()

        return url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["carrinho"] = Carrinho.objects.all()

        return context


class CarrinhoCreate(LoginRequiredMixin, CreateView):
    model = Carrinho
    fields = ["produto", "quantidade"]
    template_name = "cadastros/form.html"
    success_url = reverse_lazy("listar-carrinho")
    extra_context = {"titulo": "Adicionar item ao Carrinho"}


class PedidoList(LoginRequiredMixin, ListView):
    model = Pedido
    template_name = "cadastros/list/pedido.html"
    paginate_by = 50

    # Melhora no desempenho da consulta, isso é um INNER JOIN no atributo CLIENTE
    def get_queryset(self):
        return Pedido.objects.all().select_related("cliente")


class CarrinhoList(LoginRequiredMixin, ListView):
    model = Carrinho
    template_name = "cadastros/list/carrinho.html"
    paginate_by = 50


class ProdutoPedidoList(LoginRequiredMixin, ListView):
    model: ProdutoPedido
    template_name = "cadastros/list/produto_pedido.html"

    def get_queryset(self):
        return ProdutoPedido.objects.filter(pedido__pk=self.kwargs["pk_pedido"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["pedido"] = Pedido.objects.get(pk=self.kwargs["pk_pedido"])

        return context


class CarrinhoUpdate(LoginRequiredMixin, UpdateView):
    model = Carrinho
    fields = ["produto", "quantidade"]
    template_name = "cadastros/form.html"
    success_url = reverse_lazy("listar-carrinho")


class PedidoDelete(LoginRequiredMixin, DeleteView):
    model = Pedido
    template_name = "cadastros/delete.html"
    success_url = reverse_lazy("listar-pedido")


class CarrinhoDelete(LoginRequiredMixin, DeleteView):
    model = Carrinho
    template_name = "cadastros/delete.html"
    success_url = reverse_lazy("listar-carrinho")


class ClienteAutocomplete(LoginRequiredMixin, autocomplete.Select2QuerySetView):
    def get_queryset(self):
        object_list = Cliente.objects.all()

        if self.q:
            object_list = object_list.filter(
                nome__icontains=self.q
            )

        return object_list

cadastros/templates/cadastros/delete.html
{% extends "paginas/modelo.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<h1 class="mt-5">{{titulo|default:"Excluir"}}</h1>

<form action="" method="post">
    {% csrf_token %}

    <p>
        Tem certeza que deseja excluir este registro: <b>{{object}}</b>
    </p>


    <button type="submit" class="btn btn-danger">Excluir</button>
</form>

{% endblock %}

cadastros/templates/cadastros/form.html
{% extends "paginas/modelo.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<h1 class="mt-5">{{titulo|default:"Cadastro"}}</h1>

<form action="" method="post">
    
    {% csrf_token %}

    {{ form|crispy }}
    

    <button type="submit" class="btn btn-success">Salvar</button>
</form>

{% endblock %}

{% block scripts %}

<script src="{% static 'js/jquery.mask.js' %}"></script>

<script>
    $(document).ready(function () {

        $("#x, #y, .z").attr("type", "text");
        $("#x, #y, .z").addClass("numeros");
        
        $("#id_cpf").mask("000.000.000-00");
        $("#id_cep").mask("00000-000");
        $("input[name*=data]").mask("00/00/0000");
        $('#id_valor_total').mask('000.000.000.000.000,00', { reverse: true });

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
            spOptions = {
                onKeyPress: function (val, e, field, options) {
                    field.mask(SPMaskBehavior.apply({}, arguments), options);
                }
            };

        $('#id_telefone').mask(SPMaskBehavior, spOptions);

        // Consulta o CEP com Ajax
        $("#id_cep").blur(function (e) {

            // Limpa os campos
            $("#id_logradouro").val("");
            $("#id_bairro").val("");
            $("#id_cidade").val("");

            var cep = $("#id_cep").val();

            if (cep.length < 9) {
                return;
            }

            $("#div_id_cep").append(
                '<section class="dots-container">' +
                '<div class="dot"></div>' +
                '<div class="dot"></div>' +
                '<div class="dot"></div>' +
                '<div class="dot"></div>' +
                '<div class="dot"></div>' +
                '</section>'
            );

            var url = "https://viacep.com.br/ws/" + cep + "/json/";

            $.getJSON(url, "",
                function (data, textStatus, jqXHR) {

                    if (data.erro != true) {
                        $("#id_logradouro").val(data.logradouro);
                        $("#id_bairro").val(data.bairro);
                        $("#id_cidade").val(data.localidade + "/" + data.uf);
                        $("#id_numero").focus();
                    }


                }
            );

        });

    });

    
</script>

{% endblock %}

cadastros/templates/cadastros/form_pedido.html
{% extends "paginas/modelo.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<h1 class="mt-5">{{titulo|default:"Formulário"}}</h1>

<div class="table-responsive-lg">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Código</th>
                <th>Produto</th>
                <th>Quantidade</th>
                <th>Preço</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in carrinho %}
            <tr class="">
                <td>{{ obj.pk }}</td>
                <td>{{ obj.produto.nome }}</td>
                <td>{{ obj.quantidade }}</td>
                <td>{{ obj.produto.preco }}</td>
            </tr>
            {% empty %}
            <tr>
                <th colspan="100%">Nenhum item adicionado ao Carrinho de Compras.</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<form action="" method="post">
    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-success">{{descricao_botao|default:"Salvar"}}</button>
</form>

{% endblock %}

{% block scripts %}
{{ form.media }}
{% endblock %}